---
mysql_version: 5.7
mysql_config:
  mysqld:
    long_query_time: '1'
    slow-query-log-file: '/var/log/mysql/mysql-slow.log'
# mysql_root_username:
# mysql_root_password:
mysql_change_root_password: yes
mysql_users:
  - username: 'admin'
    password: ''
    privileges: '*.*:ALL,GRANT'
  - username: 'ro'
    password: ''
    privileges: '*.*:SELECT'
