---
- name: Install Aptitude Packages
  apt:
    name:
      - python-apt
      - aptitude
    state: latest
  tags:
    - server
    - apt

# https://github.com/ansible/ansible-modules-core/issues/3523
- name: Upgrade System
  apt:
    upgrade: yes
    update_cache: yes
  tags:
    - server
    - upgrade

- name: Install NTP
  apt:
    name: ntp
    state: present
  tags:
    - server
    - ntp

- name: Setup System Clock and Timezone
  shell: "{{ item }}"
  with_items:
    - timedatectl set-local-rtc "{{ server_rtc }}"
    - timedatectl set-ntp "{{ server_ntp }}"
    - timedatectl set-timezone "{{ server_timezone }}"
  tags:
    - server
    - ntp

- name: Generate Locale
  shell: locale-gen "{{ server_locale }}"
  tags:
    - server
    - locale

- name: Install Unattended Upgrade Package
  apt:
    name: unattended-upgrades
    state: latest
  tags:
    - server
    - unattended-upgrades

- name: Copy Unattended Upgrade Configuration
  copy:
    src: unattended-upgrades
    dest: /etc/apt/apt.conf.d/02periodic
    owner: root
    group: root
    mode: 0644
  tags:
    - server
    - unattended-upgrades

- name: Enable UFW
  ufw:
    state: enabled
    logging: on

- name: Configure UFW
  ufw:
    rule: allow
    port: ssh

- name: Disable SSH Root Login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin no'
  notify: Restart SSH Daemon
  when: server_disable_ssh_root_login

- name: Disable SSH Password Login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^#?PasswordAuthentication', line: 'PasswordAuthentication no' }
    - { regexp: '^#?PermitEmptyPasswords', line: 'PermitEmptyPasswords no' }
  notify: Restart SSH Daemon
  when: server_disable_ssh_password_login

- name: Install ResolvConf
  apt:
    name: resolvconf
    state: present
  tags:
    - server
    - dns

# https://askubuntu.com/questions/1012641/dns-set-to-systemds-127-0-0-53-how-to-change-permanently/1012648#1012648
- name: Add Base DNS Name Servers
  lineinfile:
    dest: /etc/resolvconf/resolv.conf.d/head
    line: 'nameserver {{ item }}'
  with_items: "{{ server_dns }}"
  tags:
    - server
    - dns

- name: Update ResolvConf
  shell: resolvconf -u
  become: yes
  tags:
    - server
    - dns

- name: Fix VM Networking Issues
  cron:
    cron_file: vbox_networking
    user: root
    name: 'Fix VM Networking Issues'
    job: 'rm /etc/udev/rules.d/70-persistent-net-rules && /etc/init.d/networking restart'
    special_time: reboot
    state: present
  when: server_fix_vm_networking
