---
- name: Install Aptitude Packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - python-apt
    - aptitude

# https://github.com/ansible/ansible-modules-core/issues/3523
- name: Upgrade System
  apt:
    upgrade: yes
    update_cache: yes

- name: Install NTP
  apt:
    name: ntp
    state: present

- name: Setup System Clock and Timezone
  shell: "{{ item }}"
  with_items:
    - timedatectl set-local-rtc "{{ server_rtc }}"
    - timedatectl set-ntp "{{ server_ntp }}"
    - timedatectl set-timezone "{{ server_timezone }}"

- name: Generate Locale
  shell: locale-gen "{{ server_locale }}"

- name: Install Unattended Upgrade Package
  apt:
    name: unattended-upgrades
    state: latest

- name: Copy Unattended Upgrade Configuration
  copy:
    src: unattended-upgrades
    dest: /etc/apt/apt.conf.d/02periodic
    owner: root
    group: root
    mode: 0644

- name: Install System Packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - build-essential
    - software-properties-common
    - bash-completion
    - curl
    - wget
    - ncdu
    - tree
    - whois
    - siege
    - nmap
    - cloc
    - htop
    - fail2ban
    - mosh

- name: Install Archive Packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - zip
    - unzip
    - p7zip
    - p7zip-full

- name: Install NFS Packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - nfs-common
    - portmap
  when: is_vm

- name: Install VCS Packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - git
    - git-core
    - subversion
    - mercurial

- name: Enable UFW
  ufw:
    state: enabled
    logging: on

- name: Configure UFW
  ufw:
    rule: allow
    port: ssh

- name: Disable SSH Root Login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin no'
  notify: Restart SSH Daemon

- name: Disable SSH Password Login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^#?PasswordAuthentication', line: 'PasswordAuthentication no' }
    - { regexp: '^#?PermitEmptyPasswords', line: 'PermitEmptyPasswords no' }
  notify: Restart SSH Daemon
  when: is_vm === false

- name: Add Base DNS Name Servers
  lineinfile:
    dest: /etc/resolvconf/resolv.conf.d/base
    line: 'nameserver {{ item }}'
  with_items: "{{ server_dns }}"

- name: Update ResolvConf
  shell: resolvconf -u
  notify: Restart Networking

- name: Fix VM Networking Issues
  cron:
    cron_file: vbox_networking
    user: root
    name: 'Fix VM Networking Issues'
    job: 'rm /etc/udev/rules.d/70-persistent-net-rules && /etc/init.d/networking restart'
    special_time: reboot
    state: present
  when: is_vm
