---
- name: Install System Packages
  apt:
    name:
      - build-essential
      - software-properties-common
      - bash-completion
      - curl
      - wget
      - ncdu
      - tree
      - whois
      - siege
      - nmap
      - cloc
      - htop
      - fail2ban
      - mosh
    state: latest

- name: Install Archive Packages
  apt:
    name:
      - zip
      - unzip
      - p7zip
      - p7zip-full
    state: latest

- name: Install NFS Packages
  apt:
    name:
      - nfs-common
      - nfs-kernel-server
      - portmap
    state: latest
  when: server_nfs

- name: Add Git PPA
  apt_repository:
    repo: "{{ packages.git_ppa }}"
    state: present

- name: Install VCS Packages
  apt:
    name:
      - git
      - mercuial
    state: latest
    update_cache: yes

- name: Install Packer
  unarchive:
    src: "https://releases.hashicorp.com/packer/{{ packages.packer_version }}/packer_{{ packages.packer_version }}_linux_amd64.zip"
    remote_src: yes
    dest: /usr/local/bin
    owner: root
    group: root
    mode: 0755