---
- name: Add MySQL Repository
  apt:
    deb: https://dev.mysql.com/get/mysql-apt-config_0.8.13-1_all.deb

# https://geert.vanderkelen.org/2018/mysql8-unattended-dpkg/
- name: Set Debian MySQL Configuration
  debconf:
    name: "{{ item.name }}"
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  with_items:
    - name: mysql-community-server
      question: mysql-community-server/root-pass
      value: "{{ mysql_root_password }}"
      vtype: password
    - name: mysql-community-server
      question: mysql-community-server/re-root-pass
      value: "{{ mysql_root_password }}"
      vtype: password

- name: Install MySQL
  apt:
    name:
      - mysql-server
      - mysql-client
      - python-mysqldb
    state: latest
    update_cache: yes
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Install Python3 MySQL Packages
  apt:
    name:
      - python3-dev
      - python3-pip
      - libmysqlclient-dev
    state: latest
  when: ansible_python_interpreter is defined

# https://github.com/PyMySQL/mysqlclient-python/issues/218
- name: Install Python3 MySQL Pip Packages
  pip:
    name: git+https://github.com/PyMySQL/mysqlclient-python.git
    state: present
  when: ansible_python_interpreter is defined

- name: Update MySQL Configuration
  ini_file:
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    section: mysqld
    option: "{{ item.key }}"
    value: "{{ item.value }}"
    create: yes
    backup: yes
  with_dict: "{{ mysql_config.mysqld }}"
  notify: Restart MySQL

- name: Copy MySQL Root User Configuration
  template:
    src: my.cnf.j2
    dest: /home/{{ user_account }}/.my.cnf
    owner: "{{ user_account }}"
    group: "{{ user_account }}"
    mode: 0600

- name: Update MySQL Users
  mysql_user:
    host: localhost
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    priv: "{{ item.privileges }}"
    update_password: always
    state: present
  with_items: "{{ mysql_users }}"
