---
server_disable_ssh_password_login: false
server_fix_vm_networking: false
user_account: ziadoz
mysql_root_username: 'root'
mysql_root_password: 'flipflop'
nginx_path_owner: ziadoz
nginx_path_group: ziadoz