---
- name: Build Development Environment
  hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - { role: swap, when: is_vm }
    - { role: server }
    - { role: users }
    - { role: php }
    - { role: nginx }
    - { role: certbot }
    - { role: mysql }
    - { role: ruby }
    - { role: nodejs }
    - { role: go }
    - { role: chrome, when: is_vm }
