---
- name: Build Environment
  hosts: all
  become: yes
  roles:
    - role: swap
      tags: swap-role
      when: inventory_hostname in groups['development']

    - role: server
      tags: server-role

    - role: users
      tags: user-role

    - role: php
      tags: php-role

    - role: nginx
      tags: nginx-role

    - role: certbot
      tags: certbot-role

    - role: mysql
      tags: mysql-role
      when: inventory_hostname in groups['development']

    - role: ruby
      tags: ruby-role
      when: inventory_hostname in groups['development']

    - role: nodejs
      tags: nodejs-role

    - role: go
      tags: go-role
      when: inventory_hostname in groups['development']

    - role: chrome
      tags: chrome-role
      when: inventory_hostname in groups['development']
