---
- name: Build Development Environment
  hosts: all
  become: yes
  #vars_files:
    #- vars/vault.yml
  gather_facts: False
  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      register: output
      changed_when: output.stdout != ""
      tags: always
    - setup: # aka gather_facts
  roles:
    - { role: swap, when: is_vm }
    - { role: server }
    - { role: php }
    - { role: nginx }
    - { role: mysql }
    - { role: ruby }
    - { role: nodejs }
    - { role: go }
    - { role: chrome }
