---
- name: Build Development Environment
  hosts: all
  become: yes
  #vars_files:
    #- vars/vault.yml
  roles:
    - { role: swap, when: is_vm }
    - { role: server }
    - { role: php }
    - { role: nginx }
    - { role: mysql }
    - { role: ruby }
    - { role: nodejs }
    - { role: go }
    - { role: chrome }
