---
- name: Add Caddy PPA
  apt_repository:
    repo: "deb [trusted=yes] https://apt.fury.io/caddy/ /"
    state: present

- name: Install Caddy
  apt:
    name:
      - libnss3-tools
      - caddy
    state: latest
    update_cache: yes

# https://caddy.community/t/caddy-v2-php-7-2/8657
- name: Update Caddy Group
  user:
    name: caddy
    groups: www-data
    append: yes
  notify: Stop Caddy

# sudo setcap CAP_NET_BIND_SERVICE=+eip $(which caddy)
- name: Enable Port 443
  shell: setcap CAP_NET_BIND_SERVICE=+eip $(which caddy)