---
- name: Install Dependencies
  apt:
    name: software-properties-common
    state: latest

- name: Add Certbot PPA
  apt_repository:
    repo: ppa:certbot/certbot

- name: Install Certbot
  apt:
    name: python-certbot-nginx
    state: latest
    update_cache: yes
