---
- name: Install Dependencies
  apt:
    name: software-properties-common
    state: latest

- name: Add Certbot PPA
  apt_repository:
    repo: "{{ certbot_ppa }}"
    update_cache: yes

- name: Install Certbot
  apt:
    name: python-certbot-nginx
    state: latest
